import {INLINE_STYLE, BLOCK_TYPE, ENTITY_TYPE} from 'draft-js-utils';

export const BLOCKS = {
	ATOMIC: BLOCK_TYPE.ATOMIC,
	BLOCKQUOTE: BLOCK_TYPE.BLOCKQUOTE,
	CODE: BLOCK_TYPE.CODE,
	HEADER_FIVE: BLOCK_TYPE.HEADER_FIVE,
	HEADER_FOUR: BLOCK_TYPE.HEADER_FOUR,
	HEADER_ONE: BLOCK_TYPE.HEADER_ONE,
	HEADER_SIX: BLOCK_TYPE.HEADER_SIX,
	HEADER_THREE: BLOCK_TYPE.HEADER_THREE,
	HEADER_TWO: BLOCK_TYPE.HEADER_TWO,
	ORDERED_LIST_ITEM: BLOCK_TYPE.ORDERED_LIST_ITEM,
	PULLQUOTE: BLOCK_TYPE.PULLQUOTE,
	UNORDERED_LIST_ITEM: BLOCK_TYPE.UNORDERED_LIST_ITEM,
	UNSTYLED: BLOCK_TYPE.UNSTYLED
};

export const STYLES = {
	BOLD: INLINE_STYLE.BOLD,
	CODE: INLINE_STYLE.CODE,
	ITALIC: INLINE_STYLE.ITALIC,
	STRIKETHROUGH: INLINE_STYLE.STRIKETHROUGH,
	UNDERLINE: INLINE_STYLE.UNDERLINE
};

export const ENTITIES = {
	LINK: ENTITY_TYPE.LINK
};

export const MUTABILITY = {
	MUTABLE: 'MUTABLE',
	IMMUTABLE: 'IMMUTABLE',
	SEGMENTED: 'SEGMENTED'
};


export const STYLE_SET = [
	STYLES.BOLD,
	STYLES.CODE,
	STYLES.ITALIC,
	STYLES.STRIKETHROUGH,
	STYLES.UNDERLINE
];

export const BLOCK_SET = [
	BLOCKS.ATOMIC,
	BLOCKS.BLOCKQUOTE,
	BLOCKS.CODE,
	BLOCKS.HEADER_FIVE,
	BLOCKS.HEADER_FOUR,
	BLOCKS.HEADER_ONE,
	BLOCKS.HEADER_SIX,
	BLOCKS.HEADER_THREE,
	BLOCKS.HEADER_TWO,
	BLOCKS.ORDERED_LIST_ITEM,
	BLOCKS.PULLQUOTE,
	BLOCKS.UNORDERED_LIST_ITEM,
	BLOCKS.UNSTYLED
];


//TODO: point all the references to draft-js-utils to constants in here,
//then remove the dependency on draft-js-utils
